### ISSUE TITLE
Renaming PDF fields doesn't seem to work on fields used more than once

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/FormFyxer#123]
I.e. if the there's two fields with the same name, the tool can't seem to rename any of them, even if all of the renames that you give to each are the same name. Gonna take a quick look at this now, it wasn't blocking, but did confuse me for a bit.

**Comment by nonprofittechy** [comment]
I guess now Docassemble can fill PDFs with multiples of the same field name, but that wasn't historically true. Maybe we can also fix this issue if QPDF supports it.

**Comment by BryceStevenWilley** [comment]
It turned out to be an easy fix. It's one field from the PDF perspective, but it just has `Kids` that are shown in different places. We weren't able to rename it because we were expecting certain fields to be present that weren't, so we were just skipping over those fields.
