### ISSUE TITLE
using spacy.cli.download() causes 502 gateway timeout in Docassemble

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/FormFyxer#24]
https://github.com/SuffolkLITLab/FormFyxer/blob/0b2ed81ac958b35ee4acc5972a6f6bc24b1138d6/formfyxer/lit_explorer.py#L38

**Comment by nonprofittechy** [comment]
I think it just takes too long to run. The old method of using bash at least let it eventually complete.

**Comment by BryceStevenWilley** [comment]
Fixed in https://github.com/SuffolkLITLab/FormFyxer/commit/45cb2b83ed9e3ba006e17c6b67882233f9a378d6 I think.
