### ISSUE TITLE
Citations don't have useful information

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/FormFyxer#81]
Many of the citations that I've seen don't have any useful associated information with them. For example, 
here is an example of a [California that cites the code of civil procedure](https://github.com/SuffolkLITLab/FormFyxer/files/10397599/0ae4847f7b3a552e5f75d5d412bfc5ef.pdf) (in the bottom right corner).  The relevant text is `Code of Civil Procedure, § 706.124`. Because that specific regex string isn't in [reporters_db](https://github.com/freelawproject/reporters-db), eyecite only captures that the `§` character is a chapter of some sort, but only returns `UnknownCitation('§', metadata=CitationBase.Metadata(parenthetical=None))`, which by default doesn't give any of the relevant information surrounding the citation. That sort of info is important to know if we want to suggest people remove citations from forms.

My best suggestion for moving forward is to use the `index` attribute of the object to get the position in the original text, and grab at least 10 tokens before and after the symbol for context, which we can print when we print the citation. The difficulty is recreating the tokenization process (I think they include whitespace as separate tokens).

**Comment by nonprofittechy** [comment]
I sent an email about this a few months ago to the upstream team (but didn't open a corresponding issue): https://github.com/freelawproject/eyecite.
